spring:
  datasource:
    url: jdbc:h2:mem:autotix;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:schema-h2.sql
    continue-on-error: true
