spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DB:autotix}?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USER:autotix}
    password: ${MYSQL_PASSWORD:autotix}
    initialization-mode: always
    schema: classpath:schema-mysql.sql
    continue-on-error: true
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
